// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GarminFitFile struct {
	ID         int32
	Filename   pgtype.Text
	Data       []byte
	UploadedAt pgtype.Timestamptz
	UserID     pgtype.Int4
}
