// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGarminFitFileByFilename = `-- name: GetGarminFitFileByFilename :one
select id, filename, data, uploaded_at, file_category
from garmin_fit_files
where filename = $1
`

func (q *Queries) GetGarminFitFileByFilename(ctx context.Context, filename string) (GarminFitFile, error) {
	row := q.db.QueryRow(ctx, getGarminFitFileByFilename, filename)
	var i GarminFitFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Data,
		&i.UploadedAt,
		&i.FileCategory,
	)
	return i, err
}

const getGarminFitFileByID = `-- name: GetGarminFitFileByID :one
select id, filename, data, uploaded_at, file_category
from garmin_fit_files
where id = $1
`

func (q *Queries) GetGarminFitFileByID(ctx context.Context, id int32) (GarminFitFile, error) {
	row := q.db.QueryRow(ctx, getGarminFitFileByID, id)
	var i GarminFitFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Data,
		&i.UploadedAt,
		&i.FileCategory,
	)
	return i, err
}

const insertGarminFitFile = `-- name: InsertGarminFitFile :one
insert into garmin_fit_files 
(filename, data, file_category)
values ($1, $2, $3)
returning id, filename, data, uploaded_at, file_category
`

type InsertGarminFitFileParams struct {
	Filename     string
	Data         []byte
	FileCategory NullGarminFileCategory
}

func (q *Queries) InsertGarminFitFile(ctx context.Context, arg InsertGarminFitFileParams) (GarminFitFile, error) {
	row := q.db.QueryRow(ctx, insertGarminFitFile, arg.Filename, arg.Data, arg.FileCategory)
	var i GarminFitFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Data,
		&i.UploadedAt,
		&i.FileCategory,
	)
	return i, err
}

const listGarminFilenames = `-- name: ListGarminFilenames :many
select filename
from garmin_fit_files
order by uploaded_at desc
`

func (q *Queries) ListGarminFilenames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listGarminFilenames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var filename string
		if err := rows.Scan(&filename); err != nil {
			return nil, err
		}
		items = append(items, filename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGarminFilesByFileCategory = `-- name: ListGarminFilesByFileCategory :many
select id, filename, data, uploaded_at, file_category
from garmin_fit_files
where file_category = $1
`

func (q *Queries) ListGarminFilesByFileCategory(ctx context.Context, fileCategory NullGarminFileCategory) ([]GarminFitFile, error) {
	rows, err := q.db.Query(ctx, listGarminFilesByFileCategory, fileCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GarminFitFile
	for rows.Next() {
		var i GarminFitFile
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Data,
			&i.UploadedAt,
			&i.FileCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGarminFitFilesByDateRange = `-- name: ListGarminFitFilesByDateRange :many
select id, filename, data, uploaded_at, file_category
from garmin_fit_files
where uploaded_at between $1 and $2
order by uploaded_at desc
`

type ListGarminFitFilesByDateRangeParams struct {
	UploadedAt   pgtype.Timestamptz
	UploadedAt_2 pgtype.Timestamptz
}

func (q *Queries) ListGarminFitFilesByDateRange(ctx context.Context, arg ListGarminFitFilesByDateRangeParams) ([]GarminFitFile, error) {
	rows, err := q.db.Query(ctx, listGarminFitFilesByDateRange, arg.UploadedAt, arg.UploadedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GarminFitFile
	for rows.Next() {
		var i GarminFitFile
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Data,
			&i.UploadedAt,
			&i.FileCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGarminFitFilesByFilename = `-- name: SearchGarminFitFilesByFilename :many
select id, filename, data, uploaded_at, file_category
from garmin_fit_files
where filename ilike '%' || $1 || '%'
order by uploaded_at desc
`

func (q *Queries) SearchGarminFitFilesByFilename(ctx context.Context, dollar_1 pgtype.Text) ([]GarminFitFile, error) {
	rows, err := q.db.Query(ctx, searchGarminFitFilesByFilename, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GarminFitFile
	for rows.Next() {
		var i GarminFitFile
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Data,
			&i.UploadedAt,
			&i.FileCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
